---
- name: Escaneo de Vulnerabilidades con Lynis, Analisis y Métricas.
  hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/main.yml
  pre_tasks:

  - name: Lynis Scan Vul | Valida version de Python en el/os servidor(es) remoto(s)
    include_tasks: /home/yagami/Documents/git_proyectos/comprobar_python/comprobar_python.yml

  - set_fact:
      ansible_python_interpreter: "/usr/bin/python"
    when: not usar_raw and python_version_actual >= "2.7" and python_version_actual < "3.6"

  - name: Lynis Scan Vul | Limpieza de reporte viejos
    include_tasks: tasks/limpieza_archivos.yml

  - name: Lynis Scan Vul | Se realiza descarga de Lynis.
    include_tasks: tasks/descargar_lynis.yml

  tasks:

  - name: Lynis Scan Vul | Ejecución de Lynis en el/os servidor(es) remoto(s)
    include_tasks: tasks/ejecucion_lynis.yml

  post_tasks:

  - name: Lynis Scan Vul | Analisis de reporte y obtención de métricas
    include_tasks: tasks/reporte_metricas.yml

  - name: Lynis Scan Vul | Se remueve lynis y reportes generados en el/os servidor(es) remoto(s)
    include_tasks: tasks/limpieza_remota.yml
...
