{
 "title": "Vulnerabilidades_RedHat",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cantidad total de Vulnerabilidades por S.O",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT so, SUM(cantidad) AS total_vulnerabilidades\nFROM vulnerabilidades\nWHERE categoria not in(\"Otros\")\nGROUP BY so;\n"
    }
   ]
  },
  {
   "title": "Cantidad general de Vulnerabilidades.",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT categoria, SUM(cantidad) AS total_vulnerabilidades\nFROM vulnerabilidades\nWHERE categoria not in(\"Otros\")\nGROUP BY categoria\nORDER BY total_vulnerabilidades DESC;\n"
    }
   ]
  },
  {
   "title": "Vulnerabilidades encontrada en S.O RedHat (Consolidado)",
   "type": "stat",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT categoria, SUM(cantidad) AS total_vulnerabilidades\nFROM vulnerabilidades\nWHERE so LIKE 'RedHat' AND categoria not in(\"Otros\")\nGROUP BY categoria, so\nORDER BY categoria, so;"
    }
   ]
  },
  {
   "title": "Información General ",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "mysql",
     "rawSql": "SELECT servidor SERVIDOR, categoria CATEGORIA, SUM(cantidad) AS CANTIDAD\nFROM vulnerabilidades\nWHERE categoria not in(\"Otros\")\nGROUP BY servidor, categoria\nORDER BY servidor, CANTIDAD DESC;\n"
    }
   ]
  }
 ]
}